# Generated by Django 5.0.7 on 2024-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('class_name', models.CharField(max_length=50)),
                ('mode_of_class', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50)),
                ('class_timings', models.CharField(max_length=100)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='class_images/')),
            ],
        ),
    ]
