# Generated by Django 5.0.7 on 2024-08-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='chapter_title',
            field=models.CharField(default='Untitled', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='playlist_url',
            field=models.URLField(blank=True, help_text='Enter the URL for a YouTube playlist.', null=True),
        ),
    ]
