# Generated by Django 5.0.7 on 2024-09-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
    ]
