# Generated by Django 5.0.7 on 2024-09-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
