# Generated by Django 5.0.7 on 2024-09-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_phone_number_contact_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookseat',
            name='place',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
