# Generated by Django 5.0.7 on 2024-09-11 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bookseat_created_at_bookseat_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookseat',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookseat',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookseat',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tutorial'),
        ),
    ]
