# Generated by Django 5.0.7 on 2024-09-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_bookseat_order_id_alter_bookseat_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseat',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
