# Generated by Django 5.0.7 on 2024-09-11 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_bookseat_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseat',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tutorial'),
        ),
    ]
